language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.4

before_script:
 - chmod -R +x ./scripts/

before_install: gem update --system
install: scripts/bootstrap
script: scripts/cibuild

branches:
  only:
  - master
  - develop

deploy:
  provider: pages
  local-dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

env:
  matrix:
    - JEKYLL_VERSION="~> 3.5"
    - JEKYLL_VERSION="~> 3.8.0"
    - JEKYLL_VERSION=">= 4.0.0"

sudo: false # Route your build to the container-based infrastructure for a faster build

notifications:
  email: false