language: ruby
cache: bundler
rvm: 2.6.0

before_script: chmod -R +x ./scripts/

before_install: gem update --system
install: scripts/bootstrap
script: scripts/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.5"
    - JEKYLL_VERSION="~> 3.8.0"

branches:
  only:
  - master
  - develop

jobs:
  include:
    - stage: gh page release
      rvm: 2.6.0
      before_install: gem update --system
      install: scripts/bootstrap
      script: scripts/cibuild
      env: JEKYLL_VERSION="~> 3.8.0"
      deploy:
        provider: pages
        local-dir: _site
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        target-branch: gh-pages
        on:
          branch: master
          condition: $TRAVIS_PULL_REQUEST = false
    - stage: gem release
      rvm: 2.6.0
      before_install: gem update --system
      install: scripts/bootstrap
      script: scripts/cibuild
      env: JEKYLL_VERSION="~> 3.8.0"
      deploy:
        provider: rubygems
        skip_cleanup: true
        api_key: $RUBYGEM_TOKEN
        gem: masb
        on:
          branch: master
          condition: $TRAVIS_PULL_REQUEST = false

sudo: false # Route your build to the container-based infrastructure for a faster build

notifications:
  email: false